import React from 'react';

 
    const sdata = [
        {
           imgsrc:"https://www.letstalkftball.com/image/cache/catalog/Find%20Our%20(3)-559x363.jpg",
           title:"Top Statistics for players in Major European Leagues 2022-23",
           azdate:"2023-06-23",
           username:"By Afafe",
           usermsg:"0",
           sname:"Read More",
           sparagraph:"Top goalscorers in the biggest European Leagues Player Club GS/G Goals ...",
           link:"#",
        },
        {
           imgsrc:"https://www.letstalkftball.com/image/cache/catalog/euro%20stats-559x363.jpg",
           title:"Top Statistics for Major European Leagues",
           azdate:"2023-06-20",
           username:"By Afafe",
           usermsg:"0",
           sname:"Read More",
           sparagraph:"The 2022-2023 football season has come to an end n the top European leagues, and as usual, it witnessed an intriguing struggle between ...",
           link:"#",
         },
         {
            imgsrc:"https://www.letstalkftball.com/image/cache/catalog/_arsenal-559x363.jpg",
            title:"Three big reasons for Arsenal's poor performance recently",
            azdate:"2023-06-22",
            username:"By Afafe",
            usermsg:"0",
            sname:"Read More",
            sparagraph:" Arsenal has started their current season with a greatest level of performance, topping the Premier League table from the start...",
            link:"#",
         },
         {
            imgsrc:"https://www.letstalkftball.com/image/cache/catalog/Untitled%20design-559x363.jpg",
            title:" the secret behind Chelsea's long-term signings",
            azdate:"2023-06-10",
            username:"By Afafe",
            usermsg:"0",
            sname:"Read More",
            sparagraph:" the secret behind Chelsea's long-term signings Chelsea spent more than 329 million Euros in the winter mercato to sign many heavy caliber p...",
            link:"#",
         },
         {
            imgsrc:"https://www.letstalkftball.com/image/cache/catalog/derby-559x363.jpg",
            title:"Most statistics between Alhilal and Alnassr",
            azdate:"2023-06-18",
            username:"By Afafe",
            usermsg:"0",
            sname:"Read More",
            sparagraph:"King Fahd International Stadium in Riyadh hosts the highly anticipated match between the Al-Hilal and Al-Nasr derby within the 25th round of the SRL ...",
            link:"#",
         },
         {
            imgsrc:"https://www.letstalkftball.com/image/cache/catalog/WORLDCUP/%20(2)-559x363.png",
            title:"FIFA WORLD CUP 2022 STATISTICS",
            azdate:"2023-06-18",
            username:"By Afafe",
            usermsg:"0",
            sname:"Read More",
            sparagraph:"The 2022 World Cup witnessed 29 days of exceptional events that will remain in the minds of fans of the round, beginning with the organi...",
            link:"#",
         },
         {
            imgsrc:"https://www.letstalkftball.com/image/cache/catalog/WORLDCUP/ars%201-559x363.png",
            title:"Comparison of Arsenal's level in 19 first rounds in 2003-04 and 2022-23",
            azdate:"2023-01-01",
            username:"By Afafe",
            usermsg:"0",
            sname:"Read More",
            sparagraph:"Arsenal's 2003-04 season was considered as the invincible, as the coach Arsene Wenger led his team to an unbeaten season, in their 38 league...",
            link:"#",
         },

         {
            imgsrc:"https://www.letstalkftball.com/image/cache/catalog/Articles/photo_6012669995395430773_y-559x363.jpg",
            title:"The Europa League knockout round play-off draw",
            azdate:"2023-01-23",
            username:"By Afafe",
            usermsg:"0",
            sname:"Read More",
            sparagraph:"UEFA Europa League knockout round play-off draw This season has witnessed the absence of big clubs from the round of 16 of the Champions Leagu...",
            link:"#",
         },
         {
            imgsrc:"https://www.letstalkftball.com/image/cache/catalog/Articles/photo_6012669995395430773_y-559x363.jpg",
            title:"UEFA Champions League round of 16 draw",
            azdate:"2023-11-10",
            username:"By Afafe",
            usermsg:"0",
            sname:"Read More",
            sparagraph:"UEFA announced the results of the Champions League round of 16 draw for the 23-2022 season, which was held in the Swiss city of Nyon at UEFA head...",
            link:"#",
         },
         {
            imgsrc:"https://www.letstalkftball.com/image/cache/catalog/bigest-transfers-559x363.png",
            title:"La Liga biggest transfers",
            azdate:"2022-07-31",
            username:"By Afafe",
            usermsg:"0",
            sname:"Read More",
            sparagraph:"La Liga biggest transfers 2022-23 La Liga: Will the debts prevent them from entering the transfer market? The transfer markets opened thei...",
            link:"#",
         },
         {
            imgsrc:"https://www.letstalkftball.com/image/cache/catalog/12-%E2%80%93-1-559x363.png",
            title:"LaLiga Fixtures",
            azdate:"2022-06-30",
            username:"By Afafe",
            usermsg:"0",
            sname:"Read More",
            sparagraph:"LaLiga Fixtures 2022-23 La Liga has revealed the start of the league schedule for the new season 2022/2023 in its ninety-second edition of the La L...",
            link:"#",
         },
         {
            imgsrc:"https://www.letstalkftball.com/image/cache/catalog/DARWIN-HAALIAND-CANE-559x363.png",
            title:"premier league summer transfer",
            azdate:"2022-07-15",
            username:"By Afafe",
            usermsg:"0",
            sname:"Read More",
            sparagraph:"Premier League most important summer transfers 2022-23 The end of each season in the European leagues announces the beginning of a new ra...",
            link:"#",
         },
         {
            imgsrc:"https://www.letstalkftball.com/image/cache/catalog/Banner-559x363.png",
            title:"Premier league fixtures",
            azdate:"2022-06-30",
            username:"By Afafe",
            usermsg:"0",
            sname:"Read More",
            sparagraph:":Premier league fixtures 2022-23   جدول مباريات الدوري الإنجليزي 2023 - الجولة الأولى المباراة الموعد ...",
            link:"#",
         },
         {
            imgsrc:"https://www.letstalkftball.com/image/cache/catalog/bigest-transfers-559x363.png",
            title:"الستي و ليفربول",
            azdate:"2022-05-29",
            username:"By",
            usermsg:"0",
            sname:"Read More",
            sparagraph:"...",
            link:"#",
         },
         {
            imgsrc:"https://www.letstalkftball.com/image/cache/catalog/europe_countries_5-559x363.gif",
            title:"من الافضل في اوروبا؟",
            azdate:"2022-02-23",
            username:"By Administrator",
            usermsg:"0",
            sname:"Read More",
            sparagraph:"...",
            link:"#",
         },
         {
            imgsrc:"https://www.letstalkftball.com/image/cache/catalog/WORLDCUP/ars%201-559x363.png",
            title:"كافيه الهلال والنصر",
            azdate:"2021-07-09",
            username:"By Administrator",
            usermsg:"0",
            sname:"Read More",
            sparagraph:"مقهى الهلال والنصر هو المكان الذي يجتمع فيه مشجعين الناديين العريقين لكي يتناقشوا ويتمازحوا. هذا المقهى هو المكان المناسب للمشجعين لان المعلومات المطل...",
            link:"#",
         },
         
       
   ];

   export default sdata; 
